'use client';

import type { Metadata } from "next";
import { Epilogue } from 'next/font/google';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import "./globals.css";
import { useState, ReactNode } from 'react'
import Navbar from "@/components/Navbar";
import NoiseBackground from "@/components/layout/NoiseBackground";

const epilogue = Epilogue({
  variable: "--font-epilogue",
  subsets: ["latin"],
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({ children }: { children: ReactNode }) {
  const [queryClient] = useState(() => new QueryClient());

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`p-4 bg-[#010B13] text-cyan-50 ${epilogue.variable}`}>
        {/* <QueryClientProvider client={queryClient}> */}
        <NoiseBackground />
        <Navbar />
        <main className="p-4">{children}</main>
        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}