'use client';

import type { Metadata } from "next";
import { Epilogue } from 'next/font/google';
import localFont from 'next/font/local';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import "./globals.css";
import { useState, ReactNode } from 'react'
import Navbar from "@/components/Navbar";
import NoiseBackground from "@/components/layout/NoiseBackground";

const epilogue = Epilogue({
  variable: "--font-epilogue",
  subsets: ["latin"],
});

const cc = localFont({
  src: [
    {
      path: '../../public/fonts/CourierPrime-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/CourierPrime-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-courier',
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({ children }: { children: ReactNode }) {
  const [queryClient] = useState(() => new QueryClient());

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`p-4 bg-secondary text-foreground ${epilogue.variable} ${cc.variable}`}>
        <Navbar />
        <QueryClientProvider client={queryClient}>
        {/* <NoiseBackground /> */}
        <main className="p-4">{children}</main>
        </QueryClientProvider>
      </body>
    </html>
  );
}